TuitionWala/urls.py
from django.urls import path
from django_filters.views import FilterView

from . import views
from .filters import EnrollmentFilter

app_name = 'TuitionWala'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.RegistrationForm),
    path('about', views.about),
    path('user_login', views.user_login, name='user_login'),
    path('contact', views.contact),
    path('main_page', views.main_page, name='main_page'),
    path('partner_institutions', views.partner_institutions, name='partner_institutions'),
    path('inst1', views.inst1),
    path('inst2', views.inst2),
    path('inst3', views.inst3),
    path('inst4', views.inst4),
    path('inst5', views.inst5),
    path('inst6', views.inst6),
    path('inst7', views.inst7),
    path('inst8', views.inst8),
    path('inst9', views.inst9),
    path('inst10', views.inst10),
    path('fburl', views.fburl),
    path('enrollment_console', views.table),
    path('enrollment_form', views.EnrollmentForm),
    path('enrollment_consoled', views.tablew),
    path('status', views.status),
    path('Entity_Registration_Form', views.Entity_Registration_Form)
]

django_mentormind_boilerplate/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic import TemplateView
from TuitionWala import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('index/', include('TuitionWala.urls')),
    path('logout/', views.user_logout,name='logout'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
]

templates/insts/inst1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>TuitionWala</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->

    <link rel="shortcut icon" href="{% static 'images/book.ico' %}" type="image/x-icon" >
    <link rel="apple-touch-icon" href="{% static 'images/book1.png' %}" type="image" >


    <link rel="shortcut icon" href="images/book.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <title>TutionWala</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav id="navmain" class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6e6;">
      <a class="navbar-brand" href="#"></a>
            <img src="{% static 'uploads/logonavbar.png' %}">
      </a>
<!-- Brand and toggle get grouped for better mobile display -->
<!-- This is the actual code that creates the "hamburger icon" -->
<!-- The data-target grabs ids to put into the icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->
         <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/main_page">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="http://127.0.0.1:8000/index/partner_institutions">Partner Institutions</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/Entity_Registration_Form">Register(Institute/Tutor)</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/enrollment_console">Click To Enroll</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/status">Enrollment Status</a>
              </div>


              </div>

              </div>
                          </div> <!-- /.navbar-nav, left-hand content -->
        <!-- STUFF ON THE RIGHT -->
<form class="logout" action="http://127.0.0.1:8000/index">
              <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'TuitionWala:user_login' %}">Login</a>
            {% endif %}
            </div> <!-- /.navbar-nav, right-hand content -->

            </div> <!-- /.navbar-collapse -->
  </form>
</nav>
    <div class="jumbotron">
    <div class="card card-body">
      <h2> Vivekananda foundation</h2>
        <b><center><img id="inst1" src="{% static 'images/inst1.png' %}" alt="" width=200px height=100px></center></b>
        <p></p>
          <p> <b>Vivekananda foundation</b> was established with the specific aim of making people  learn how to use the language correctly and effectively. This foundation has come up with  excellence of course with twenty years of research in global language. It has offered a unique  way of teaching the language in a simple and  <br>suitable way to the different categories of learners such  as students, employees, professionals, executives, business men and housewives.
      We Provide Tailor-Made Language Courses Online For Companies, Individuals, Small Groups And Job  Seekers. Learn Languages In A Small Group Course With Students, Employees, Professionals, Executives, Business Men And Housewives And The Ambitious.
      <ul>
        <p><b><u>Contact Us:-</u></b></p>
        <li>Email us : info@vivekanandafoundation.com</li>
      <li>Call us on:+91 9121002737, 9121002397</li>
      <li>ADDRESS:-</li>
      H.O: KPHB (Kuktapally)
      Flat No: 401, Padmaja's Raja Enclave, Beside KS Bakers, KPHB, Hyderabad - 72
      B.O: Ameerpet
      Flat No: 401, Prashanthi Ram Towers, Near Sarathi Studio, Yousuyguda Road, Hyderabad - 45
      B.O Mehdipatnam
      Flat No: 404, 4th Floor, Sakina Complex, Mehdipatnam X Road, Hyderabad - 28
      </ul>
      </p>
      <p></p>
      <p></p>
      <p align=right><a class="btn btn-primary btn-lg" href="http://127.0.0.1:8000/index/partner_institutions" role="button">Go Back</a></p>
      </div>
    </div>
  </body>
</html>

templates/insts/inst10.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>TuitionWala</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->

    <link rel="shortcut icon" href="{% static 'images/book.ico' %}" type="image/x-icon" >
    <link rel="apple-touch-icon" href="{% static 'images/book1.png' %}" type="image" >


    <link rel="shortcut icon" href="images/book.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <title>TutionWala</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav id="navmain" class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6e6;">
      <a class="navbar-brand" href="#"></a>
            <img src="{% static 'uploads/logonavbar.png' %}">
      </a>
<!-- Brand and toggle get grouped for better mobile display -->
<!-- This is the actual code that creates the "hamburger icon" -->
<!-- The data-target grabs ids to put into the icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->
         <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/main_page">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="http://127.0.0.1:8000/index/partner_institutions">Partner Institutions</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/Entity_Registration_Form">Register(Institute/Tutor)</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/enrollment_console">Click To Enroll</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/status">Enrollment Status</a>
              </div>


              </div>

              </div>
                          </div> <!-- /.navbar-nav, left-hand content -->
        <!-- STUFF ON THE RIGHT -->
<form class="logout" action="http://127.0.0.1:8000/index">
              <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'TuitionWala:user_login' %}">Login</a>
            {% endif %}
            </div> <!-- /.navbar-nav, right-hand content -->

            </div> <!-- /.navbar-collapse -->
  </form>
</nav>
    <div class="jumbotron">
    <div class="card card-body">
      <h2>HEMTOR Institute</h2>
        <b><center><img id="inst10"src="{% static 'images/inst10.png' %}" alt="" width=200px height=100px></center></b>
        <p></p>
          <b><u>HEMTOR Institute</u></b> , Established in the year 2013, Hemtor Learning Pvt Ltd in Nallakunta, Hyderabad is a top player in the category IIT Tutorials in the Hyderabad. This well-known establishment acts as a one-stop destination servicing customers both local and from other parts of Hyderabad. Over the course of its journey, this business has established a firm foothold in it’s industry. The belief that customer satisfaction is as important as their products and services, have helped this establishment garner a vast base of customers, which continues to grow by the day. This business employs individuals that are dedicated towards their respective roles and put in a lot of effort to achieve the common vision and larger goals of the company. In the near future, this business aims to expand its line of products and services and cater to a larger client base.</p>
      <ul>
        <p><b><u>Contact Us:-</u></b></p>
            <li><b><u>Mobile No:-</u></b>9152529862</li>
            <p></p>
            <li><b><u>ADDRESS:-</u></b>Flat No 401, 2-1-565, Vertex Paradigm University Road, Nallakunta, Hyderabad - 500044, Above Nandini Hotel.</li>
      </ul>
      </p>
      <p></p>
      <p></p>
      <p align=right><a class="btn btn-primary btn-lg" href="http://127.0.0.1:8000/index/partner_institutions" role="button">Go Back</a></p>
      </div>
    </div>
  </body>
</html>

templates/insts/inst2.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>TuitionWala</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->

    <link rel="shortcut icon" href="{% static 'images/book.ico' %}" type="image/x-icon" >
    <link rel="apple-touch-icon" href="{% static 'images/book1.png' %}" type="image" >


    <link rel="shortcut icon" href="images/book.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <title>TutionWala</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav id="navmain" class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6e6;">
      <a class="navbar-brand" href="#"></a>
            <img src="{% static 'uploads/logonavbar.png' %}">
      </a>
<!-- Brand and toggle get grouped for better mobile display -->
<!-- This is the actual code that creates the "hamburger icon" -->
<!-- The data-target grabs ids to put into the icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->
         <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/main_page">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="http://127.0.0.1:8000/index/partner_institutions">Partner Institutions</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/Entity_Registration_Form">Register(Institute/Tutor)</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/enrollment_console">Click To Enroll</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/status">Enrollment Status</a>
              </div>


              </div>

              </div>
                          </div> <!-- /.navbar-nav, left-hand content -->
        <!-- STUFF ON THE RIGHT -->
<form class="logout" action="http://127.0.0.1:8000/index">
              <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'TuitionWala:user_login' %}">Login</a>
            {% endif %}
            </div> <!-- /.navbar-nav, right-hand content -->

            </div> <!-- /.navbarcollapse -->
  </form>
</nav>
    <div class="jumbotron">
    <div class="card card-body">

    <h2>Raga Tution</h2>
      <b><center><img id="inst2" src="{% static 'images/inst2.png' %}" alt=""></center></b>
      <p></p>
      <p><b>Ragatuitions</b> is an online portal which connects parents/students and private tutors in Hyderabad and Secunderabad on a common platform, wherein they can discover/search each other with ease. The students and home tutors can also request call back and our customer support team can get them registered for free. Alternatively, users register on their own via our website. Students as well as tuition teachers in Hyderabad can look for each other directly through our website and contacting each other through call/SMS or email. Ours is a very unique business model - as soon as a new parent/student registers, the relevant details like subject, class, contact number as well as location will be sent by SMS and e-mail to all the relevant home tutors in Hyderabad, which match the requirements. Then the home tuition teachers can contact the student on the provided number to discuss further. The students can then ask for a demo class from tutors, and if its deemed satisfactory, the student and tutor can finalise things like tuition fees, timings, frequency of classes and the other terms directly. We have a huge database of students and tutors. Students as well as home tuition teachers in Secunderabad and Hyderabad can search this database of ours and find each other by contacting each other via our website. The contact numbers are also provided which can be used to contact each other directly.
      <ul>
      <p><b><u>Contact Us:-</u></b></p>
      <li><b><u>ADDRESS:-</b></u> D.no #8-3-319/8/4,
      S9,Block 3,Sri Nilayam,
      Near Sarathi Studio,
      Ameerpet
      Hyderabad - 500073
      India</li>
      </ul>
      </p>
      <p></p>
      <p></p>
      <p align=right><a class="btn btn-primary btn-lg" href="http://127.0.0.1:8000/index/partner_institutions" role="button">Go Back</a></p>

      </div>

    </div>

  </body>
</html>

templates/insts/inst3.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>TuitionWala</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->

    <link rel="shortcut icon" href="{% static 'images/book.ico' %}" type="image/x-icon" >
    <link rel="apple-touch-icon" href="{% static 'images/book1.png' %}" type="image" >


    <link rel="shortcut icon" href="images/book.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <title>TutionWala</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav id="navmain" class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6e6;">
      <a class="navbar-brand" href="#"></a>
            <img src="{% static 'uploads/logonavbar.png' %}">
      </a>
<!-- Brand and toggle get grouped for better mobile display -->
<!-- This is the actual code that creates the "hamburger icon" -->
<!-- The data-target grabs ids to put into the icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->
         <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/main_page">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="http://127.0.0.1:8000/index/partner_institutions">Partner Institutions</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/Entity_Registration_Form">Register(Institute/Tutor)</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/enrollment_console">Click To Enroll</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/status">Enrollment Status</a>
              </div>


              </div>

              </div>
                          </div> <!-- /.navbar-nav, left-hand content -->
        <!-- STUFF ON THE RIGHT -->
<form class="logout" action="http://127.0.0.1:8000/index">
              <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'TuitionWala:user_login' %}">Login</a>
            {% endif %}
            </div> <!-- /.navbar-nav, right-hand content -->

            </div> <!-- /.navbarcollapse -->
  </form>
</nav>
    <div class="jumbotron">

    <div class="container">

    <h2>BRILLIANT ACADEMY</h2>

    <p></p>
    <p> <b>BRILLIANT ACADEMY</b> has been providing students of HYDERABAD with quality education since 2012. BA was the pioneer in dealing with engineering & diploma tuitions in Hyderabad. Having 5 years of experience we were decided to take a step further. Brilliant Academy has started under the dynamic leadership of academician Mr. JAGADEESH .He aimed to provide classroom coaching to hundreds of aspirants. In the journey of 5 years, Brilliant Academy has grown from strength to strength. Brilliant Academy taught more than 1500 students to get their degree with good score. BA has always focused on adapting with time and provides all the help and support to students so that they achieve nothing but the best in their professional careers.
    We helped 1500 students, who had supplies ranging from 10 subjects to 30 subjects. We do have personalized counseling for students who have a lot of back papers to identify their weakness and to help them to plan their future exam seasons.
    BRILLIANT ACADEMY is a result-oriented institute which believes in giving best results for students who are suffering with backlogs & top results for students who are interested in learning the concepts.
    </p>
    <ul>
    <p><b><u>Contact Us:-</u></b></p>
      <li><b><u>Mobile No:-</u></b> (+91) 7842104103,(+91)040-40269619</li>
      <p></p>
      <li><b><u>Email ID:-</u></b> :- info@mybrilliantacademy.com, reachus@mybrilliantacademy.com, admin@mybrilliantacademy.com</li>
      <p></p>
    <li><b><u>ADDRESS:-</u></b>503, Nandini Residency,
    Above Airtel Office, Addagutta society,
    Opp to JNTU,KPHB
    Hyderabad-500072
    </li>
    </ul>
      <p align=right><a class="btn btn-primary btn-lg" href="http://127.0.0.1:8000/index/partner_institutions" role="button">Go Back</a></p>

      </div>

    </div>

  </body>
</html>

templates/insts/inst4.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

     <!-- Site Metas -->
    <title>TuitionWala</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->

    <link rel="shortcut icon" href="{% static 'images/book.ico' %}" type="image/x-icon" >
    <link rel="apple-touch-icon" href="{% static 'images/book1.png' %}" type="image" >


    <link rel="shortcut icon" href="images/book.ico" type="image/x-icon" />
    <meta charset="utf-8">
    <title>TutionWala</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav id="navmain" class="navbar navbar-expand-lg navbar-light" style="background-color: #e6e6e6;">
      <a class="navbar-brand" href="#"></a>
            <img src="{% static 'uploads/logonavbar.png' %}">
      </a>
<!-- Brand and toggle get grouped for better mobile display -->
<!-- This is the actual code that creates the "hamburger icon" -->
<!-- The data-target grabs ids to put into the icon -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->
         <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/main_page">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" href="http://127.0.0.1:8000/index/partner_institutions">Partner Institutions</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/Entity_Registration_Form">Register(Institute/Tutor)</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/enrollment_console">Click To Enroll</a>
          <a class="nav-item nav-link" href="http://127.0.0.1:8000/index/status">Enrollment Status</a>
              </div>


              </div>

              </div>
                          </div> <!-- /.navbar-nav, left-hand content -->
        <!-- STUFF ON THE RIGHT -->
<form class="logout" action="http://127.0.0.1:8000/index">
              <div class="navbar-nav ml-auto">
              {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'TuitionWala:user_login' %}">Login</a>
            {% endif %}
            </div> <!-- /.navbar-nav, right-hand content -->

            </div> <!-- /.navbar-collapse -->
  </form>
</nav>
    <div class="jumbotron">
    <div class="card card-body">
      <h2>The Melhore Institute</h2>
      <b><center><img id="inst4" src="{% static 'images/inst4.png' %}" alt=""></center></b>
      <p></p>
      <p><b><u>The Melhore Institute</u></b></p>
      <ul style="list-style-type:disc;">
      <li ><b><u>School Coaching</u></b></li>
      <p>Here’s a secret that the lots of training schools would not let you know: 80%* of life and business coaches are less than pleased with their coaching businesses.</p>
      <li><b><u>Home Tutions</u></b></li>
      <p>We offer intensive one to one language courses in the homes of trainers around the India. Outside of the lessons, from breakfast to bedtime, you live and eat with the family in their home.</p>
      <li><b><u>Corporate Training</u></b></li>
      <p>The ability to converse with worldwide business associates in their language can have a direct impact on your abundance.</p>
      <p><b><u>Contact Us:-</u></b></p>


      </ul>
      <ul>


      <li><b><u>Mobile No:-</u></b> 0091 9885643254, 0091 40 65443254</li>
      <p></p>
      <li><b><u>Email ID:-</u></b> :- info@melhorinstitute.com, md@melhorinstitute.com</li>
      <p></p>
      <li><b><u>ADDRESS:-</u></b>6-3-1086/VGT/601, 6th Floor,
      Vista Grand Towers,
      Above Adishwar Electronics,
      Raj Bhavan Road, Somajiguda,
      </li>
      </ul>
      <p></p>

        <p align=right><a class="btn btn-primary btn-lg" href="http://127.0.0.1:8000/index/partner_institutions" role="button">Go Back</a></p>

      </div>

    </div>

  </body>
</html>